language: go

go:
  - '1.11'
  - '1.12'
  - stable
  - master

env:
  global:
    - GO111MODULE=on

addons:
  postgresql: "10"

matrix:
  allow_failures:
    - go: master

script:
  - go get -u golang.org/x/lint/golint
  - test -z "$(golint ./...)"
  - test -z "$(gofmt -l .)"
  - createuser pgmgr -s
  - go test -v ./...
